# Generated by Django 3.2 on 2021-05-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_booking_model_booked_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_model',
            name='want_to_book_the_slot',
        ),
    ]
